#!/usr/bin/env bash
export SCRIPTPATH=$( cd "$(dirname "$0")" ; pwd -P )

xrandr -s 1920x1080

#if path to liblinkt is not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Start eww daemon with config
path="$SCRIPTPATH/eww"
eww -c $path daemon &

# Boot picom
picom --experimental-backends &> /dev/null &

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
feh --bg-scale $SCRIPTPATH/wallpaper.jpg

# Open eww bar window
eww -c $path open bar
