#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")"; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

$HOME/.config/eww/script/menu launch

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"